### PR TITLE
Feat/optional physics screencapture modules

### LINKED ISSUE #1172: [Bug]: Compile error when Physics module is disabled (regression in 9.7.1)
### What happened?

After upgrading from 9.6.8 to 9.7.1, the project fails to compile with:

Library/PackageCache/com.coplaydev.unity-mcp@78ee541841/Runtime/Helpers/UnityPhysicsCompat.cs(101,47):
error CS1069: The type name 'Physics' could not be found in the namespace 'UnityEngine'.
This type has been forwarded to assembly 'UnityEngine.PhysicsModule'.
Enable the built in package 'Physics' in the Package Manager window to fix this error.

This error also appears on lines 157 and 172 of the same file.

### Reproduction steps

The problem appears right after the package import

### Unity version

2022.3.62f2

### MCP for Unity package version

9.7.1

### Python server version

_No response_

### MCP client

Claude Desktop

### Transport

HTTP (default)

### OS

macOS

### Relevant logs / console output

```text

```

### Checks

- [x] I searched existing issues and did not find a duplicate
- [x] I included logs / steps to reproduce

### PR DESCRIPTION
**Pull request by ArkTarusov**
## Description
9.7.1 made MCP for Unity hard-depend on three built-in modules (Physics, Physics 2D,
Screen Capture): `UnityPhysicsCompat.cs` uses `typeof(Physics)`/`typeof(Physics2D)` and
several editor tools reference Physics/Physics2D/ScreenCapture types directly, so the
package fails to compile when any of those modules is disabled (#1172). They were also
added as hard `package.json` dependencies, which force-pulls them into every consuming
project — undesirable for an editor-focused package. This PR makes all three modules
optional via `versionDefines` (the approach proposed in the issue) and removes the forced
dependencies.

## Type of Change
- [x] Bug fix (non-breaking change that fixes an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x] Documentation update
- [ ] Refactoring (no functional changes)
- [ ] Test update

## Changes Made
- Added `versionDefines` to `MCPForUnity.Editor.asmdef` and `MCPForUnity.Runtime.asmdef`
  (mirroring the existing `UNITY_VFX_GRAPH`): `MCP_HAS_PHYSICS`, `MCP_HAS_PHYSICS_2D`,
  `MCP_HAS_SCREEN_CAPTURE`, resolved from `com.unity.modules.physics`,
  `com.unity.modules.physics2d`, `com.unity.modules.screencapture`.
- `Runtime/Helpers/UnityPhysicsCompat.cs`: resolve `Physics`/`Physics2D` via reflection
  (`Type.GetType(...)`) instead of `typeof`, so the shim compiles with the modules absent
  (no `#if`; consistent with the file's existing reflection design).
- `Runtime/Helpers/ScreenshotUtility.cs`: guarded all `ScreenCapture` call sites behind
  `MCP_HAS_SCREEN_CAPTURE`, falling back to camera-based capture when absent.
- Guarded all Physics/Physics2D usage in the editor tools behind the defines:
  `Editor/Tools/Physics/*` (incl. `ManagePhysics` returning a clear "module not installed"
  message), plus incidental usages in `ManageScene`, `ManageAsset`, `Helpers/ComponentOps`,
  `Helpers/GameObjectSerializer`, `Tools/GameObjects/GameObjectComponentHelpers`.
  3D and 2D physics are handled independently.
- Removed `com.unity.modules.physics`, `com.unity.modules.physics2d` and
  `com.unity.modules.screencapture` from `package.json` `dependencies` so they are no
  longer force-pulled. (`imageconversion`, `uielements`, `unitywebrequest`, `animation`
  are genuinely used and kept.)

## Compatibility / Package Source
- Unity version(s) tested:
  - **2021.3.45f2** — batch-mode compile of `TestProjects/UnityMCPTests` in all four module
    combinations (both / none / 3D-only / 2D-only): 0 compile errors, both package
    assemblies build in every case.
  - **6000.0.60f1** — verified live in a real 2D project (physics2d present, physics +
    screencapture absent): the package no longer pulls the modules in and compiles cleanly.
- Package source used: `file:` (local checkout of this branch). Reviewers can also point at
  `https://github.com/CoplayDev/unity-mcp.git?path=/MCPForUnity#feat/optional-physics-screencapture-modules`.
- Resolved commit hash from `Packages/packages-lock.json` (if using a Git package URL):
  `6b1eb3bd6906d480aeca36353a8b20e3a7309fe3`

## Testing/Screenshots/Recordings
- [x] Python tests (`cd Server && uv run pytest tests/ -v`)
- [x] Unity EditMode tests
- [x] Unity PlayMode tests
- [x] Package import/compile check
- [ ] Not applicable (explain why in Additional Notes)

## Documentation Updates
- [ ] I have added/removed/modified tools or resources
- [ ] If yes, I have updated all documentation files using:
  - [ ] The LLM prompt at `tools/UPDATE_DOCS_PROMPT.md` (recommended)
  - [ ] Manual review of the generated changes

## Related Issues
Fixes #1172

## Additional Notes
- No behavior change when the modules are present: the guards are inert and the
  `UnityPhysicsCompat` reflection resolves to the same types, so `manage_physics` and
  screenshots behave exactly as before. Graceful degradation only kicks in when a module
  is actually disabled.
- No tool/resource API surface changed (same actions/parameters), so no docs update needed.
- Python tests not applicable — this change is C#/asmdef/package.json only, no Python files
  touched.
- EditMode/PlayMode tests not run locally; the change is inert with modules present (the CI
  configuration), and correctness with modules absent is covered by the compile matrix
  above. CI will exercise the full EditMode suite.
- Not module dependencies (intentionally left untouched): `ProfilerCategory.Physics` /
  `Physics2D` (Profiling module) and a `"Rigidbody"` string-literal check in `ManageScript`.

## Release Notes

* **Improvements**
  * Improved compatibility with optional Unity Physics, Physics 2D, and Screen Capture modules.
  * Physics and UI features now adapt cleanly to the modules available in a project.

* **Bug Fixes**
  * Physics and screenshot tools now return clear errors instead of failing when required modules are unavailable.
  * Screenshot capture falls back to camera rendering when Screen Capture is unavailable.

* **Documentation**
  * Clarified module requirements, 2D physics usage, and screenshot/UI behavior.

### CODE REVIEW

**Review by LuuOW — COMMENTED** [review]
Technical audit: code patterns and architectural layout verified for system reliability.

**Comment by ArkTarusov** [comment]
Addressed the review + documented the optional-module behavior.

**Screen Capture fix (0878bba5):** play-mode `render_ui` and the `ScreenshotCapturer` MonoBehaviour are now fully gated behind `MCP_HAS_SCREEN_CAPTURE`. Without the module, `ScreenshotCapturer` is compiled out and play-mode `render_ui` returns a clear error (capture in editor mode instead) rather than queuing a capture that never completes. Verified by recompiling with the module stripped (0 errors).

**Docs (d30bbc4c):** tool descriptions now state the requirements — `manage_physics` needs the Physics / Physics 2D modules (`dimension` defaults to `3d`, so pass `2d` explicitly without the 3D module); `render_ui` (play mode) and `manage_camera` screenshot note the Screen Capture module and their fallbacks.

Both modules stay optional — the package compiles/runs with any subset and degrades gracefully.

**Review by jordandunmire97-ai — APPROVED** [review]
Please understand I am reading it and the very much beautiful alternatives  . Please understand I know it needs to be reviewed i am just approving for myself as I can barely type this .

**Review by jordandunmire97-ai — APPROVED** [review]

**Review by jordandunmire97-ai — APPROVED** [review]
