### ISSUE TITLE
v9.6.4 compile error: ErrorResponse type missing in ManageTexture / ManagePrefabs / MemorySnapshotOps

### ISSUE THREAD

**Issue by c0sogi** [CoplayDev/unity-mcp#1020]
## Environment
- unity-mcp version: `9.6.4`
- package commit: `61521a26b7a85c67ef18d99f802f9ae5d154a3a1`
- Unity version: 2022.3.17f1
- Install method: Git UPM package (https://github.com/CoplayDev/unity-mcp.git?path=/MCPForUnity#main)

## Problem
After updating to `v9.6.4`, Unity fails to compile the package because `ErrorResponse` cannot be resolved from multiple package files under `Library/PackageCache`.

## Errors
```text
Library\PackageCache\com.coplaydev.unity-mcp@61521a26b7\Editor\Tools\Profiler\Operations\MemorySnapshotOps.cs(193,24): error CS0246: The type or namespace name 'ErrorResponse' could not be found (are you
missing a using directive or an assembly reference?)

Library\PackageCache\com.coplaydev.unity-mcp@61521a26b7\Editor\Tools\ManageTexture.cs(34,24): error CS0246: The type or namespace name 'ErrorResponse' could not be found (are you missing a using directive or
an assembly reference?)

Library\PackageCache\com.coplaydev.unity-mcp@61521a26b7\Editor\Tools\Prefabs\ManagePrefabs.cs(728,40): error CS0246: The type or namespace name 'ErrorResponse' could not be found (are you missing a using
directive or an assembly reference?)

Library\PackageCache\com.coplaydev.unity-mcp@61521a26b7\Editor\Tools\Prefabs\ManagePrefabs.cs(975,39): error CS0246: The type or namespace name 'ErrorResponse' could not be found (are you missing a using
directive or an assembly reference?)

Library\PackageCache\com.coplaydev.unity-mcp@61521a26b7\Editor\Tools\Prefabs\ManagePrefabs.cs(1153,43): error CS0246: The type or namespace name 'ErrorResponse' could not be found (are you missing a using
directive or an assembly reference?)
```

## Notes

- This does not appear to come from project code. The errors are inside the package cache for com.coplaydev.unity-mcp.
- The issue started after updating to v9.6.4 / commit 61521a26b7.
- It looks like either:
  - ErrorResponse was removed/renamed but references were left behind, or
  - the type exists in another assembly/namespace but is no longer visible from these files.

## Expected

The package should compile cleanly after installation/update.

## Actual

Unity cannot finish compilation, so the package is unusable in the editor.

**Comment by Jinghu006** [comment]
I have the same compile issue, my unity version is 2021.3.21f1

**Comment by Scriptwonder** [comment]
PR#1025 should also fix this, looks like a GUID conflict. Let me know if the error still remains.

**Comment by c0sogi** [comment]
Confirmed fixed on v9.6.5 from the upstream main package.

I replaced the package with the upstream 9.6.5 version and the previous `CS0246` compile errors for `ErrorResponse` no longer 
reproduce in my Unity project.

Looks like PR #1025 / the GUID conflict fix resolved it. Thanks.
