### ISSUE TITLE
Cannot work on unity 2021.3.32

### ISSUE THREAD

**Issue by kurolykin** [CoplayDev/unity-mcp#118]
Excuse me，does these eidtors needs different configuration？It could work on unity 2022,and the Readme said the required version is above 2020. I think that it shoud work on 2021
![Image](https://github.com/user-attachments/assets/d2a592e4-204a-4b02-95ec-cdb34d9a380b)  It could work on unity 2022

![Image](https://github.com/user-attachments/assets/ce73c3a2-ea1a-4c6d-94de-423b82f911e1) But couldn't work on unity 2021.3.32
 These are both empty projects without compilation error reports

**Comment by amicharnoff** [comment]
following

**Comment by jiangshan1xiao** [comment]
2022 and newer

**Comment by itspers** [comment]
why then it says 'Unity Hub & Editor: Version 2020.3 LTS or newer.' in readme...

**Comment by pigubaoza** [comment]
same on 2020.3.42f1

**Comment by msanatan** [comment]
@kurolykin what didn't work for you?

1. I installed the plugin
2. Connected the server
3. Use WIndSurf to do a very basic test - create 2 cubes

It worked. Just needed to confirm everything was connected. I'm on MacOS and Unity version 2021.3.19.

<img width="805" height="766" alt="Image showing Unity MCP plugin connected" src="https://github.com/user-attachments/assets/c966e299-f7a6-4d54-8326-62d2216c0c93" />

<img width="405" height="845" alt="Image showing request in WindSurf" src="https://github.com/user-attachments/assets/75e77599-16fa-4bc3-885f-2a7ca9251de9" />

<img width="1379" height="616" alt="Image showing result in Unity" src="https://github.com/user-attachments/assets/8da20fb8-66b0-4402-b63d-b7bf58d78614" />

It's possible that an update may have fixed your issues

**Comment by dsarno** [comment]
Anyone try this on PC? Would be good to confirm it works there too. Pathing and environment setup can differ on two platforms like they do with Claude code and Cursor setups

**Comment by dsarno** [comment]
Hi all, try again using the just-released `2.0.0` version of the MCP, which has major improvements to setup and mcp bridge/server configuration. You should **reinstall the package in Unity** because there's a new package name and address.  I'm going to close this but can reopen if you still see problems.

```
1. Open your Unity project.
2. Go to Window > Package Manager.
2. Click + -> Add package from git URL....
Enter:
https://github.com/CoplayDev/unity-mcp.git?path=/UnityMcpBridge
```
