### PR TITLE
fix: BuildReport.SummarizeErrors() compile error on Unity 2022.3

### LINKED ISSUE #984: `BuildReport.SummarizeErrors()` causes CS1061 compile error on Unity 2022.3 (and all versions below 2023.1)
**Package:**  
com.coplaydev.unity-mcp (main branch, commit 3dd5ac7742)

**Unity Version:**  
2022.3.42f1 (LTS)

**Error:**  
```csharp
Library\PackageCache\com.coplaydev.unity-mcp@3dd5ac7742\Editor\Tools\Build\BuildRunner.cs(115,47): error CS1061: 
'BuildReport' does not contain a definition for 'SummarizeErrors' and no accessible extension method 'SummarizeErrors' 
accepting a first argument of type 'BuildReport' could be found 
(are you missing a using directive or an assembly reference?)

### PR DESCRIPTION
**Pull request by zaferdace**
## Summary

Fixes #984

`BuildReport.SummarizeErrors()` was introduced in **Unity 2023.1**, but the preprocessor guard used `UNITY_2022_3_OR_NEWER`, causing a `CS1061` compile error on Unity 2022.3 LTS.

## Changes

- Extracted error message logic into a `GetBuildErrorMessage()` helper method
- Changed the version guard from `UNITY_2022_3_OR_NEWER` to `UNITY_2023_1_OR_NEWER`
- Added empty string fallback since `SummarizeErrors()` can return empty on some build failures
- Added error count fallback (`"{n} build error(s)"`) for pre-2023.1 Unity versions, providing more useful info than the previous generic message

## Affected Versions

| Unity Version | Before | After |
|---------------|--------|-------|
| 2022.3 LTS | CS1061 compile error | Falls back to error count / result message |
| 2023.1+ | Works | Works (with empty string safety) |
| Unity 6 (6000.x) | Works | Works (with empty string safety) |

## Test Plan

- [ ] Verify compilation on Unity 2022.3 LTS
- [ ] Verify `SummarizeErrors()` works on Unity 2023.1+
- [ ] Verify fallback message on failed builds (pre-2023.1)

## Summary by Sourcery

Fix build error handling across Unity versions by centralizing error message generation and correcting the version guard for BuildReport.SummarizeErrors.

Bug Fixes:
- Resolve CS1061 compile error on Unity 2022.3 by guarding usage of BuildReport.SummarizeErrors with the correct Unity 2023.1+ preprocessor symbol.
- Ensure builds that fail on Unity 2023.1+ handle empty responses from BuildReport.SummarizeErrors safely.

Enhancements:
- Introduce a shared GetBuildErrorMessage helper to provide consistent, informative build failure messages across Unity versions, including an error count fallback when available.

### CODE REVIEW

**Comment by Scriptwonder** [comment]
This is fixed in the latest beta, which we use the same solution to just use Unity 2023.1 as the fail guard. Will close it.
