### ISSUE TITLE
[Bug]: Compile Error without com.unity.modules.screencapture package

### ISSUE THREAD

**Issue by LovorDev** [CoplayDev/unity-mcp#1176]
### What happened?

What happened?
After upgrading from 9.6.8 to 9.7.1, the project fails to compile with:

Library\PackageCache\com.coplaydev.unity-mcp@efaf786e8772\Runtime\Helpers\ScreenshotUtility.cs(269,23): error CS0103: The name 'ScreenCapture' does not exist in the current context

Windows

### Reproduction steps

Install package without dependency
It appear after compile try

### Unity version

 6000.3.10f

### MCP for Unity package version

9.7.1

### MCP client

Codex

### Transport

HTTP (default)

### OS

Windows

### Relevant logs / console output

```text

```

### Checks

- [x] I searched existing issues and did not find a duplicate
- [x] I included logs / steps to reproduce

**Comment by Scriptwonder** [comment]
Enable it in Unity Package Manager will help. Also, if you uninstall the package and install will also work.
