### ISSUE TITLE
[Bug]: Compile error when Physics module is disabled (regression in 9.7.1)

### ISSUE THREAD

**Issue by Ommand** [CoplayDev/unity-mcp#1172]
### What happened?

After upgrading from 9.6.8 to 9.7.1, the project fails to compile with:

Library/PackageCache/com.coplaydev.unity-mcp@78ee541841/Runtime/Helpers/UnityPhysicsCompat.cs(101,47):
error CS1069: The type name 'Physics' could not be found in the namespace 'UnityEngine'.
This type has been forwarded to assembly 'UnityEngine.PhysicsModule'.
Enable the built in package 'Physics' in the Package Manager window to fix this error.

This error also appears on lines 157 and 172 of the same file.

### Reproduction steps

The problem appears right after the package import

### Unity version

2022.3.62f2

### MCP for Unity package version

9.7.1

### MCP client

Claude Desktop

### Transport

HTTP (default)

### OS

macOS

### Relevant logs / console output

```text

```

### Checks

- [x] I searched existing issues and did not find a duplicate
- [x] I included logs / steps to reproduce

**Comment by Scriptwonder** [comment]
Is this from the latest build? We try to optimize the process by enabling some packages from the start today, this might cause an issue from earlier builds, but should be fine from the latest build. Also are you intentionally want to disable the physics? Enabling it should resolve this error.

**Comment by Ommand** [comment]
How do I check the build number? I've updated the package to 9.7.1 via Package Manager. 

And yes, my project intentionally does not have the physics package installed.

**Comment by Scriptwonder** [comment]
> How do I check the build number? I've updated the package to 9.7.1 via Package Manager. 
> 
> And yes, my project intentionally does not have the physics package installed.
> 

I think if you update it from UPM in the beta branch it should be the latest.
Reason behind intentionally not install it? My intention is with the current package.json it will auto-install packages for users, so we can get rid of some reflection-based codes that impose some complexities.

**Comment by Ommand** [comment]
I have no issues on 9.7.2-beta8, thanks a lot. The reason is that I build for mobile platforms, and the physics package adds a few megabytes to the build, which I’d prefer not to include.

**Comment by Ommand** [comment]
It seems that I have no issues because the physics package is now included as a dependence. That's not exactly what I intended to achieve though.

**Comment by Scriptwonder** [comment]
Any way you could build and ship it without the package (since it only results in compilation errors during editor mode, and I assume you are not shipping Unity-MCP with your game)?

**Comment by Ommand** [comment]
That is correct, but wouldn't I have to keep the package in unstaged changes forever this way? Or to remove it before the build procedure.

**Comment by ArkTarusov** [comment]
I’m running into the same issue after updating to the current version.

On top of that, the `ScreenCapture` dependency is missing.

This is frustrating for an editor-focused package. Runtime/module dependencies directly affect Unity project compatibility, even when the package is mainly intended to help agents work inside the Unity Editor.

This could probably be handled through `versionDefines`, so physics-related code is only compiled when the Physics module is actually available.

I’ll try to verify this assumption soon and submit a PR with a proposed fix.

**Comment by Scriptwonder** [comment]
> I’m running into the same issue after updating to the current version.
> 
> On top of that, the `ScreenCapture` dependency is missing.
> 
> This is frustrating for an editor-focused package. Runtime/module dependencies directly affect Unity project compatibility, even when the package is mainly intended to help agents work inside the Unity Editor.
> 
> This could probably be handled through `versionDefines`, so physics-related code is only compiled when the Physics module is actually available.
> 
> I’ll try to verify this assumption soon and submit a PR with a proposed fix.

Ideally, these packages should be installed on a fresh install for new users, but I do think having these in the final package is unneeded (even for the benefits of removing all related compilation errors during usage)

Feel free to submit a clean PR that could address this issue, thanks!

**Comment by ArkTarusov** [comment]
Hi, @Scriptwonder ! I sent a pull request about this issue, but I'm not getting any response. Could you take a look at it and tell me what's missing?
